language: go
sudo: false
go:
  - 1.11
  - 1.10
  - 1.9
  - 1.8
  - tip
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2
  - 1.1
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email:
    on_success: never
matrix:
  fast_finish: true