language: go
sudo: false
go:
  - tip
  - 1.11
  - "1.10"
  - 1.9
  - 1.8
  - 1.6
  - 1.5
  - 1.4
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email:
    on_success: never
matrix:
  fast_finish: true